### ISSUE TITLE
На страницах Услуги, О нас, Контакты уменьшить высоту section 1, потому что картинка плохо выглядит

### ISSUE THREAD

**Issue by anleshch** [Cheewbacca/BudPartner#131]
http://joxi.ru/LmG6E3zUg4gdPr

**Comment by Byelmanov** [comment]
@quallrum could you please check this background, because on localhost it looks good on both chrome dev tools (mobile view) and mobile. Had some problems with that on safari and chrome (on iPhone) so added script build/static/js/fixBgAttachmentFixed.js maybe you forgot to add it
![IMG_BA0E22AC8F47-1](https://user-images.githubusercontent.com/51419058/127550013-0ae1e14f-7fc2-4ff6-8eee-ddbcfb67dbc3.jpeg)

**Comment by quallrum** [comment]
Have added this script to Services and Contacts pages, didnt notice any changes. Please review it on perfect Apple devices as script should work only on them. 

Here is how it looks like on Androind's Chrome

![image](https://user-images.githubusercontent.com/34860412/127900869-94830264-70c0-46e3-bb20-0aa6ca411197.png)

**Comment by Byelmanov** [comment]
Thank you. It works on GitHub pages, but need also to check it on production environment when production will be ready

**Comment by Byelmanov** [comment]
@quallrum It is not working on production, but works on github-pages

**Comment by quallrum** [comment]
@Byelmanov could you please provide more information about steps to reproduce this problem? The list of included scripts are almost the same on my local server, demo server and Github Pages, with the only difference of additional CMS scripts. So, to check if they are the root of the problem I need to know how to reproduce the bug locally in order to try reproduce it with and without those scipts.

**Comment by Byelmanov** [comment]
@quallrum it can be triggered only using iPhone, please try to investigate this problem, because it's strange that it works on localhost and GitHub-pages
